import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout'
export default function Home() {
  return (
    
    <div className={styles.container}>
      <Head>
        <title>ثانويه عروه بن الزبير بنين</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
     
      <main className={styles.main}>
        <h1 className={styles.title}>
         مرحبا بكم في ثانويه  عروه بن الزبير
        </h1>

        <p className={styles.description}>
          لتسجيل الدخول
        </p>


      </main>

  </div>
    
  )
}
Home.getLayout = function getLayout(page) {
  return (
    <Layout>
      
    </Layout>
  )
}
